from regression import PoseRegressor
import numpy as np
from utils import setupGPU, readRenderData, readCocoLikeData
import cv2

if __name__ == '__main__':
	setupGPU()

	print('Loading training data...')
	#X01, y01 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_01/", use_depth=True)
	#X02, y02 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_02/", use_depth=True)
	#X03, y03 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_03/", use_depth=True)
	#X04, y04 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_04/", use_depth=True)
	#X05, y05 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_05/", use_depth=True)
	#X06, y06 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_06/", use_depth=True)
	#X07, y07 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_07/", use_depth=True)
	#X08, y08 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_08/", use_depth=True)
	#X09, y09 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_09/", use_depth=True)
	#X10, y10 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_10/", use_depth=True)
	#X11, y11 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_11/", use_depth=True)
	#X12, y12 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_12/", use_depth=True)
	#X13, y13 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/strawberries_13/", use_depth=True)
	#X14, y14 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_01/", use_depth=True)
	#X15, y15 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_02/", use_depth=True)
	#X16, y16 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_03/", use_depth=True)
	#X17, y17 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_04/", use_depth=True)
	#X18, y18 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_05/", use_depth=True)
	#X19, y19 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_06/", use_depth=True)
	#X20, y20 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_07/", use_depth=True)
	#X21, y21 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_08/", use_depth=True)
	#X22, y22 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_09/", use_depth=True)
	#X23, y23 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_10/", use_depth=True)
	#X24, y24 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_11/", use_depth=True)
	#X25, y25 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_12/", use_depth=True)
	#X26, y26 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_13/", use_depth=True)
	#X27, y27 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_14/", use_depth=True)
	#X28, y28 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_15/", use_depth=True)
	#X29, y29 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_16/", use_depth=True)
	#X30, y30 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/allberries_17/", use_depth=True)
	#X = np.concatenate((X01, X02), axis=0)
	#X = np.concatenate((  X, X03), axis=0)
	#X = np.concatenate((  X, X04), axis=0)
	#X = np.concatenate((  X, X05), axis=0)
	#X = np.concatenate((  X, X06), axis=0)
	#X = np.concatenate((  X, X07), axis=0)
	#X = np.concatenate((  X, X08), axis=0)
	#X = np.concatenate((  X, X09), axis=0)
	#X = np.concatenate((  X, X10), axis=0)
	#X = np.concatenate((  X, X11), axis=0)
	#X = np.concatenate((  X, X12), axis=0)
	#X = np.concatenate((  X, X13), axis=0)
	#X = np.concatenate((  X, X14), axis=0)
	#X = np.concatenate((  X, X15), axis=0)
	#X = np.concatenate((  X, X16), axis=0)
	#X = np.concatenate((  X, X17), axis=0)
	#X = np.concatenate((  X, X18), axis=0)
	#X = np.concatenate((  X, X19), axis=0)
	#X = np.concatenate((  X, X20), axis=0)
	#X = np.concatenate((  X, X21), axis=0)
	#X = np.concatenate((  X, X22), axis=0)
	#X = np.concatenate((  X, X23), axis=0)
	#X = np.concatenate((  X, X24), axis=0)
	#X = np.concatenate((  X, X25), axis=0)
	#X = np.concatenate((  X, X26), axis=0)
	#X = np.concatenate((  X, X27), axis=0)
	#X = np.concatenate((  X, X28), axis=0)
	#X = np.concatenate((  X, X29), axis=0)
	#X = np.concatenate((  X, X30), axis=0)
	#y = np.concatenate((y01, y02), axis=0)
	#y = np.concatenate((  y, y03), axis=0)
	#y = np.concatenate((  y, y04), axis=0)
	#y = np.concatenate((  y, y05), axis=0)
	#y = np.concatenate((  y, y06), axis=0)
	#y = np.concatenate((  y, y07), axis=0)
	#y = np.concatenate((  y, y08), axis=0)
	#y = np.concatenate((  y, y09), axis=0)
	#y = np.concatenate((  y, y10), axis=0)
	#y = np.concatenate((  y, y11), axis=0)
	#y = np.concatenate((  y, y12), axis=0)
	#y = np.concatenate((  y, y13), axis=0)
	#y = np.concatenate((  y, y14), axis=0)
	#y = np.concatenate((  y, y15), axis=0)
	#y = np.concatenate((  y, y16), axis=0)
	#y = np.concatenate((  y, y17), axis=0)
	#y = np.concatenate((  y, y18), axis=0)
	#y = np.concatenate((  y, y19), axis=0)
	#y = np.concatenate((  y, y20), axis=0)
	#y = np.concatenate((  y, y21), axis=0)
	#y = np.concatenate((  y, y22), axis=0)
	#y = np.concatenate((  y, y23), axis=0)
	#y = np.concatenate((  y, y24), axis=0)
	#y = np.concatenate((  y, y25), axis=0)
	#y = np.concatenate((  y, y26), axis=0)
	#y = np.concatenate((  y, y27), axis=0)
	#y = np.concatenate((  y, y28), axis=0)
	#y = np.concatenate((  y, y29), axis=0)
	#y = np.concatenate((  y, y30), axis=0)

	use_color = True
	use_depth = False
	interpolation = cv2.INTER_LANCZOS4
	X01, y01 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_01/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X02, y02 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_02/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X03, y03 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_03/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X04, y04 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_04/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X05, y05 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_05/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X06, y06 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_06/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X07, y07 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_07/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X08, y08 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_08/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X09, y09 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_09/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X10, y10 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_10/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X11, y11 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_11/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X12, y12 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_12/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X13, y13 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_13/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X14, y14 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_14/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X15, y15 = readCocoLikeData("/home/niko/Documents/git/gazebo-data-annotator/annotated_data/segmented_berries_15/", use_color=use_color, use_depth=use_depth, interpolation=interpolation)
	X = np.concatenate((X01, X02), axis=0)
	X = np.concatenate((  X, X03), axis=0)
	X = np.concatenate((  X, X04), axis=0)
	X = np.concatenate((  X, X05), axis=0)
	X = np.concatenate((  X, X06), axis=0)
	X = np.concatenate((  X, X07), axis=0)
	X = np.concatenate((  X, X08), axis=0)
	X = np.concatenate((  X, X09), axis=0)
	X = np.concatenate((  X, X10), axis=0)
	X = np.concatenate((  X, X11), axis=0)
	X = np.concatenate((  X, X12), axis=0)
	X = np.concatenate((  X, X13), axis=0)
	X = np.concatenate((  X, X14), axis=0)
	X = np.concatenate((  X, X15), axis=0)
	y = np.concatenate((y01, y02), axis=0)
	y = np.concatenate((  y, y03), axis=0)
	y = np.concatenate((  y, y04), axis=0)
	y = np.concatenate((  y, y05), axis=0)
	y = np.concatenate((  y, y06), axis=0)
	y = np.concatenate((  y, y07), axis=0)
	y = np.concatenate((  y, y08), axis=0)
	y = np.concatenate((  y, y09), axis=0)
	y = np.concatenate((  y, y10), axis=0)
	y = np.concatenate((  y, y11), axis=0)
	y = np.concatenate((  y, y12), axis=0)
	y = np.concatenate((  y, y13), axis=0)
	y = np.concatenate((  y, y14), axis=0)
	y = np.concatenate((  y, y15), axis=0)
	np.save(open('train_orientations.npy', 'wb'), y)

#	for i, img in enumerate(X):
#		img              = cv2.resize(img, (512,512))
#		arrow_startpoint = np.array((img.shape[0]/2, img.shape[1]/2))
#		n                = np.array((1,0,0))
#		dist             = np.dot(n, y[i])
#		arrow_endpoint   = (arrow_startpoint + (np.array((-1,-1)) * (y[i] - dist * n)[1:3] * arrow_startpoint)).astype(int)
#
#		cv2.arrowedLine(img, tuple(arrow_startpoint), tuple(arrow_endpoint), (0, 255, 0), thickness=5)
#		cv2.imshow("img", img[:,:,:3])
#		cv2.imwrite("berry_000.png", img[:,:,:3]) 
#		cv2.waitKey()

	model, callbacks = PoseRegressor(X[0].shape, model_name="orientation_estimator_nodepth.hdf5")
	model.fit(X, y, 
	          batch_size=128, 
	          epochs=100, 
	          verbose=1, 
	          validation_split=0.1,
	          callbacks=callbacks)